#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

rm -rf sinPureConvection_*
rm -rf ./gnuPlotData/data*
rm -rf grid_*
rm -rf log.*

#------------------------------------------------------------------------------
